src/javascript/core.js
src/javascript/event.js
src/javascript/link.js
src/javascript/page.js
src/javascript/utils.js
test/core.test.js
test/core/send.test.js
test/link.test.js
test/main.test.js
test/page.test.js

Fairly major bug, the module was "remembering" values from the previous event in the next event!

Stop oTracking retaining values between tracking events.

---

src/javascript/core.js
src/javascript/page.js
test/main.test.js

Page to event link

---

src/javascript/core/send.js
test/main.test.js

@AlbertoElias I think I've fixed IE once and for all...!

IE fixes with cross domain requests

---

docs/enrichment.md
docs/event.md
main.js
src/javascript/core.js
src/javascript/core/send.js
src/javascript/event.js
src/javascript/link.js
src/javascript/page.js
test/core.test.js
test/event.test.js
test/link.test.js
test/main.test.js
test/page.test.js

A proposal for more general model to represent page and events, and contains some thoughts on what I'd like to see the [Spoor API](https://spoor-docs.herokuapp.com) collect.

Flat model

---

docs/enrichment.md
docs/event.md

My editor removes trailing white spaces. Let me know if you'd prefer a cleaner diff :)

milliseconds

---

main.js
src/javascript/core/user.js
test/core/user.test.js
test/main.test.js

o-tracking sets spoor-id in a cookie rather than local storage

---

README.md
main.js

Make utils available on o-tracking's namespace

Public utils

---

demos/json-config.html
demos/src/json-config.mustache
origami.json

Adds suggested demo by @triblondon

More practical demo and adds it to the origami.json file

---

main.js
src/javascript/core.js
src/javascript/core/queue.js
src/javascript/core/send.js
src/javascript/core/session.js
src/javascript/core/settings.js
src/javascript/core/store.js
src/javascript/core/user.js
src/javascript/link.js
src/javascript/page.js
src/javascript/utils.js
test/core/store.test.js

Clean up after forgetting to write cookies to the 'root' ft.com domain.
- Check local storage for the 'proper' value.
- If it exists, use it.
- If not, set current user id as the 'proper' value.
- If this value and the cookie match, then we've already fixed it.
- If not, drop the cookie and it will be reset it on the root domain.

Cookie fix

---

README.md
docs/ftcom_example.md
docs/membership_example.md

- Recommended init
- Real examples.

Updated docs

---

src/javascript/utils.js

/cc @markstephens @charypar @AlbertoElias 
Fixes https://github.com/Financial-Times/o-tracking/issues/66
(there might be a more efficient way of doing this than a try/finally)

Generate fallback guid when window.crypto not defined

---

src/javascript/event.js
test/event.test.js

Gets component name from data attribute if it's an Origami component

---

origami.json

Adds required apis to origami.json

---

src/javascript/link.js
test/link.test.js

Link tracking

---

src/javascript/core.js
test/core.test.js

- Remove JS user agent as it's different from headers version.

User agent

---

main.js
src/javascript/core/send.js
test/core.test.js
test/main.test.js
test/page.test.js

- Add ability to set environment in system properties on init

Environments

---

main.js
src/javascript/core/send.js
src/javascript/events/custom.js
src/javascript/events/link-click.js
src/javascript/events/page-view.js
src/libs/browser-cuid.js
test/core.test.js
test/events/custom.test.js
test/events/link-click.test.js
test/events/page.test.js
test/main.test.js

The idea being that it provides a good foundation to gradually start importing the more diverse range of events available in n-instrumentation (https://github.com/Financial-Times/o-tracking/issues/93 is turning into a bit of a monster)

Changing directory structure

---

main.js
src/javascript/core.js
src/javascript/core/queue.js
src/javascript/core/send.js
src/javascript/core/session.js
src/javascript/core/settings.js
src/javascript/core/store.js
src/javascript/core/user.js
src/javascript/events/custom.js
src/javascript/events/link-click.js
src/javascript/events/page-view.js
src/javascript/utils.js

Fix for https://github.com/Financial-Times/o-tracking/issues/90

Fix for https://github.com/Financial-Times/o-tracking/issues/90

---

src/javascript/core/user.js

- cancel migrate across domains, fix has taken effect.

Spoor cookie

---

src/javascript/core/send.js
test/core/send.test.js

- Retain offline lag if the send fails.

Fix offline lag

---

src/javascript/core/user.js

- Bring back migrate cookie across domains
- Still affecting anon users

"Root" domain cookie

---

src/javascript/core/transports/xhr.js

see http://stackoverflow.com/a/19667959/87739. Hopefully this'll have a big effect in IE @markstephens

avoid InvalidStateErrors in IE10

---

src/javascript/core/queue.js
src/javascript/core/send.js
src/javascript/core/store.js

- IE10 can't handle putting an exception in a custom event.

Exception reporting

---

main.js
src/javascript/core/send.js
test/core/send.test.js
test/main.test.js

https://jira.ft.com/browse/DTP-330

Investigate queue lengths bug

---

src/javascript/events/page-view.js
test/events/page.test.js

Fix for events detached from a page view, if they were sent before the page view

Detached events

---

test/events/click.test.js

Re-add the lost click tests
- need updating to the new format.

Click tests

---

src/javascript/events/click.js
test/events/click.test.js

As per [this "messaging brain" doc](https://docs.google.com/document/d/1l-lUHJXcyrLCnlb44NdUyO2rs5Nj8kWpl_ZZz_Gpx5U/edit)

Add custom trackable attributes

---

src/javascript/core/send.js
test/core/send.test.js

I was building the functionality aroudn the structure of the data fixture used in tests
It turns out the fixture was not an accurate picture of reality

info in urls now fixed

---

docs/event-parameters/page-view.md
docs/event-parameters/text-copy.md
docs/membership_example.md
src/javascript/core.js

Not super-urgent but good to get in there before the old cookies go away!
Should be backwards compatible.

Prefer FTSession_s cookies over FTSession cookies as the latter are deprecated

---

src/javascript/events/click.js
test/events/click.test.js

Using `data-o-tracking-skip-queue` for skipping the queue and firing a link click straight away

---

README.md
main.js
src/javascript/events/click.js
src/javascript/utils.js

o-tracking could use some love, but in the meantime I've made a few small documentation changes that would have helped the other day.

Tweak documentation.

---

MIGRATION.md
README.md
bower.json

Reverts Financial-Times/o-tracking#215

Revert "Breaking" OOOOOOPS

---

bower.json

See https://github.com/Financial-Times/o-tracking/issues/209

Upgrade dependencies to the latest beta

---

main.js
src/javascript/core.js
src/javascript/core/queue.js
src/javascript/core/send.js
src/javascript/core/session.js
src/javascript/core/store.js
src/javascript/events/click.js
src/javascript/events/component-view.js
src/javascript/events/custom.js
src/javascript/utils.js
src/libs/browser-cuid.js
test/core.test.js
test/core/queue.test.js
test/core/send.test.js
test/core/session.test.js
test/core/store.test.js
test/events/custom.test.js
test/events/page.test.js
test/main.test.js
test/utils.test.js

This was a good way for me to get reintroduced into the codebase :-)

Fix all linting issues/warnings in the project which were found by `obt verify`

---

MIGRATION.md
README.md
docs/enrichment.md
docs/event.md
docs/membership_example.md
docs/sample-events/comments/comments-loaded-2.json
docs/sample-events/comments/comments-loaded.json
docs/sample-events/link-click.json
docs/sample-events/next-opt-in-shown.json
docs/sample-events/page-scroll.json
docs/sample-events/page-view.json
docs/sample-events/perceived-load.json
docs/sample-events/video/first-impression.json
docs/sample-events/video/playback.json
docs/sample-events/video/player-load-requested.json
docs/sample-events/video/player-load.json
docs/sample-events/video/stream.json
docs/sample-events/video/true_view.json
docs/sample-events/video/video_start.json
main.js
src/javascript/core/send.js
test/core.test.js
test/main.test.js

Chris Brown and Jaya Ananthram confirmed it is not required -- https://financialtimes.slack.com/archives/C1WF81SR3/p1594900349090600

Remove api_key because it is not needed by Spoor or o-tracking and is nearly always the same value

---

.remarkrc.js
README.md
package.json

Add readme linting

---

.remarkrc.js
README.md
package.json

The remark linter work was in a newer version of the master branch than what v3 branched off of. This pull-request pull in chee's work into the v3 branch.

Merge chee's Remark origami linter into v3

---

src/javascript/core/send.js
test/core/send.test.js

We've gathered enough data for debugging the IE11 issue now -- fixes https://github.com/Financial-Times/o-tracking/issues/187

Remove IE11 connection debugging code which we no longer require

---

README.md

Fixes https://github.com/Financial-Times/o-tracking/issues/176

 Add documentation about data-trackable and data-trackable-context-* attributes

---

src/javascript/core/queue.js
src/javascript/core/send.js
src/javascript/events/click.js
test/core.test.js
test/core/queue.test.js
test/core/send.test.js
test/events/click.test.js
test/events/custom.test.js
test/events/page.test.js
test/main.test.js

This does not effect the external interface at all

Remove the default export for Queue

---

docs/event.md

Fixes https://github.com/Financial-Times/o-tracking/issues/123

Fix the documentation about spoor enrichment adding missing propertyies to the payload

---

README.md
src/javascript/events/custom.js

fixes https://github.com/Financial-Times/o-tracking/issues/72

document that the custom event category and action properties are optional

---

.dependabot/config.yml

master branch had changes which v3 does not have

Merge master into v3 branch

---

.gitignore
test/core/send.test.js
test/events/custom.test.js

Found these when running the tests using `obt --browserstack`

Update assertions to make the tests work in ios and ie
