README.md
When viewing the readme through the registry the link to the polyfill-service directs towards  `http://registry.origami.ft.com/components/polyfill.io`.
Use an absolute link which directs the user towards `https://cdn.polyfill.io/`
=> Add absolute link to polyfill.io website

src/javascript/core.js, src/javascript/core/session.js, test/core.test.js, test/core/session.test.js
It would be useful to know whether the session has just started for data analysis, e.g. what area of the site do users begin their session, where do they come from, etc
This adds a `spoor_session_is_new` field: `true` when a session has just been created, `false` until it expires
=> Add 'is new' flag to session

src/javascript/core/store.js, src/javascript/utils.js, test/core/store.test.js
- Forgot to decode values in cookies, they're set as encoded strings
- Likely a fix for https://github.com/Financial-Times/o-tracking/issues/81 too
=> Cookie storage bug

.travis.yml, karma.conf.js, main.js, origami.json, package.json, src/javascript/core.js, src/javascript/core/send.js, src/javascript/core/store.js, src/javascript/core/transports/image.js, src/javascript/core/transports/index.js, src/javascript/core/transports/send-beacon.js, src/javascript/core/transports/xhr.js, src/javascript/events/link-click.js, src/javascript/utils.js, test/core.test.js, test/core/send.test.js, test/events/custom.test.js, test/events/link-click.test.js, test/events/page.test.js, test/main.test.js, test/setup.js
As part of this I've stopped passing anything in to the on complete callback. It's not documented what gets passed into this callback by o-tracking (and it varies depending on whether the transport is image or XHR anyway) so I think it's, if not necessarily safe, technically fine to stop passing anything in. Better might be to return a Promise, resolved or rejected on request completion/error. Depending on how careful we want to be around people's use of undocumented parameters passed to callback this may necessitate a major release, but would be a step forward worth making I think.
=> added send beacon transport

main.js, src/javascript/events/custom.js, src/javascript/events/link-click.js, src/javascript/events/page-view.js
The current implementation - where listeners are added on load - means that we can't turn o-tracking fully off with a flag as it still tries to send requests to spoor when something on the page fires an oTracking event. This throws an error because o-tracking hasn't been initialised and configured
```
Uncaught TypeError: Cannot read property 'read' of undefinedgetSession @ session.js:43track @ core.js:97event @ custom.js:67module.exports @ dispatchCustomEvent.js:16(anonymous function) @ navigation-timing.js:98setTimeout (async)load @ navigation-timing.js:21
```
@markstephens
=> only init listeners on init, not on load

docs/event-parameters/page-view.md
@markstephens Adding missing types from https://jira.ft.com/browse/AWG-31. We now have `login`, `funnel`, `account` and `membership` types, which seem to overlap and will cause confusion. Can you clarify the definition of each?
=> Add new asset types

main.js, src/javascript/events/click.js
cc @markstephens 
Click events: Merge the event data into the "parent" config data, so that they contain values that are appropriate to the moment the event occurs (rather than the moment the event's tracking request is sent)
=> Click update

Makefile, src/javascript/core/send.js
Something seems to be somehow calling o-tracking/send.js `run(callback)` with a `callback` that is an `Event` of `type:"online"`. 
I reproduced this in the `next-article` app by going offline (switching off wifi), waiting a minute, then coming back online.
I tried to find what was setting `callback` to an `Event`, with no success. So the best I can do for now is guard against any non-function callbacks.
This will hopefully reduce the "t is not a function" errors in [sentry](https://sentry.io/nextftcom/frontend/?query=is%3Aunresolved+t+is+not+a+function).
=> Only allow callbacks that are functions.

package.json, src/javascript/events/click.js, test/events/click.test.js
This change is added to support securedrop, after this change any clicks to the securedrop service should be excluded from tracking.
=> Securedrop stop tracking

README.md
Normalises capitalisation of `otracking` to `oTracking`; moves assignment of `oTracking` in the "full example" to above where it's first used.
Currently the "full example" is broken due to typos resulting from improper capitalisation of "oTracking". We ran into this in Financial-Times/shorthand-lambda#2.
=> Updates examples in README - Fixes #154

src/javascript/core/user.js
I left the ft.com match as a regex as it's by far the simplest implementation, but fixed it!
=> Improve user domain matching regex, and remove migrate_across_domains now it's no longer needed

main.js, package.json
Oops.
(Can this be automated?  Even just adding it just to package.json would be an improvement - but then require'ing it on the client side may pull in the whole package, not idea.  Do you do this in other apps at the moment?)
=> Bump the version number

main.js, test/main.test.js
- If o-tracking initialises without config, it is useless
- The auto-init from the dom event keeps racing infront of my manual init with config
- This fix aims to avoid that race and discard the init coming from the dom-event
- Obvs, if the declaritive config is set, then it will still work with `domcontentloaded`
=> Stop config-less init

docs/event-parameters/page-view.md, docs/event-parameters/text-copy.md, docs/membership_example.md, src/javascript/core.js, test/core.test.js
I'm hoping we can get this out ASAP. The previous change meant that the secure token was still being passed under the `ft_session` attribute. Unfortunately, membership have a different endpoints for validation of secure and non secure tokens `membership/sessions/s/` vs `membership/sessions/`
The previous change meant we were hitting the non secure endpoint with secure tokens and it was failing due to the invalid token type. This had the knock on affect of producing bad data at both Spoor and Ammit. 
I will make the relevant changes to use `ft_session_s` when available so hopefully we can ween ourselves off `ft_session`
@missamynicholson @rowanbeentje @Financial-Times/origami-core
=> Pass secure token under a different attribute

main.js, src/javascript/core/user.js
This allows the cookie domain to be passed in via config.
Currently, if we're not on ft.com the cookie defaults to the current domain which is fine in most cases unless we're moving across subdomains. The spoor-id on foo.example.com will be different from bar.example.com which isn't desirable in some cases.
=> Allow cookie domain to be passed in via config

src/javascript/events/click.js
The randomly generated unique id is being overridden by this and causing tracking issues.
=> Fix context id

main.js, package.json, src/javascript/core/transports/image.js
This is a test to see if IE is happier with an image response for Image transport rather than the normal html response from /ingest
See example traffic from a customer
It's recognising the AJAX method won't work and falling back to Images, which is great, but then also see the images don't make it through and are aborted.
=> Image uses image

main.js, package.json
- Including a version number within the code is not inline with the Origami spec, and should be removed in the next major (https://origami.ft.com/docs/component-spec/modules/).
=> Update version number :mask:

README.md, main.js, origami.json, src/javascript/events/click.js, src/javascript/events/component-view.js, src/javascript/utils.js, src/libs/get-trace.js, test/events/component-view.test.js, test/utils.test.js
Component view events will be fired with elements set `data-o-tracking-view` attribute or elements collected by a custom selector in `opts`. They will populate a `domPathTokens` as well as Click events. You could pass a custom category, and also a callback[`getContextData`] to collect data for events.  
:warning: This feature requires `window.IntersectionObserver` in order to track the events  
:warning: `getContextData` should be a function which returns `{Object}`
```js
const opts = {
category: 'audio', // default: 'component'
selector: '.o-teaser__audio', // default: '[data-o-tracking-view]'
getContextData: () => {  // default: null
return {
contentId: '1234',
type: 'audio',
subtype: 'podcast',
component: 'teaser'
};
}
}
oTracking.view.init(opts);
```
=> Add impression(component:view) tracking

README.md, src/javascript/events/component-view.js, test/events/component-view.test.js, test/utils.test.js
Impressions on article pages having both **contentID**(the component's content id) and **rootContentID**(the article's content id) is potentially confusing. We rename **contentID** to **componentContentID** so it is very clear what that applies to.
=> component:view tracking: Modify contentId => componentContentId

main.js, test/main.test.js
We require Markets Data to add a rootID to the page and pass it into oAds. They don't use n-ui but they do use oTracking, from the build service. This PR enables them to get a rootId for the markets data page.
=> Expose getRootID() on the oTracking object

src/javascript/events/component-view.js
I have added `console.warn` about `window.IntersectionObserve` in wrong place 😱
=> Fix wrong warning for component view

package.json
This is not allowed by the spec.
https://origami.ft.com/spec/v1/components/#npm
=> Remove the `main` field from package.json.

main.js, package.json
Thie commit removes the version number from `package.json`
to align with the Origami spec (it's currently outdated anyway).
The version number is also set in `main.js` is incorrect. This commit
updates it for the new major. It's likely to fall out of date again.
We should consider removing it in a future version of o-tracking but
first need to understand if/how it's used.
https://github.com/Financial-Times/o-tracking/issues/195
=> Remove version from `package.json`. Update version in `main.js`

main.js
Many users are including o-tracking without a semver range:
`https://build.origami.ft.com/bundles/js?modules=o-tracking`
This makes o-tracking v2 compatible with v1 for their usecase via
the build service.
=> Export the o-tracking init function.

main.js
Many users are including o-tracking without a semver range:
`https://build.origami.ft.com/bundles/js?modules=o-tracking`
This makes o-tracking v2 compatible with v1 for their usecase via
the build service.
=> Export some o-tracking functions.

src/javascript/events/component-view.js, test/events/component-view.test.js
because that's what used to be exported:
https://github.com/Financial-Times/o-tracking/blob/v1.7.3/src/javascript/events/component-view.js#L85-L87
(the init function was never the main export)
=> Export an object containing init from events/component-view

src/libs/get-trace.js
`o-tracking` uses import/export everywhere except this one in `libs/get-trace.js`.
I found this when I tried to build `n-messaging-client` using Webpack 4.
Error I got when I tried to load the bundled JS in Chrome:
```
get-trace.js:112 Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
at Module.eval (get-trace.js:112)
at eval (get-trace.js:114)
at Module../bower_components/o-tracking/src/libs/get-trace.js (main.js:525)
at __webpack_require__ (main.js:20)
at eval (click.js:8)
at Module../bower_components/o-tracking/src/javascript/events/click.js (main.js:453)
at __webpack_require__ (main.js:20)
at eval (main.js:14)
at Module../bower_components/o-tracking/main.js (main.js:309)
at __webpack_require__ (main.js:20)
```
and Webpack warned:
```
WARNING in …
```
=> Fix libs/get-trace export

test/core.test.js, test/core/queue.test.js, test/core/send.test.js, test/core/session.test.js, test/core/settings.test.js, test/core/store.test.js, test/core/user.test.js, test/events/click.test.js, test/events/component-view.test.js, test/events/custom.test.js, test/events/page.test.js, test/main.test.js, test/utils.test.js
Stop using the magic imports for proclaim and sinon and pull them from the global because that's where Karma has added them. This is required for obt v10 to be released.
=> Stop using magic webpack imports

MIGRATION.md, README.md, src/javascript/events/component-view.js, src/javascript/utils.js, test/events/component-view.test.js, test/utils.test.js
Rename variables and function to be more descriptive.
Replace reduce function which generates an object via Object.assign with a for-of loop.
=> Refactor: rename whitelistProps to filterProperties and replace reduce with a for-of loop

bower.json, origami.json, src/javascript/core/store.js, src/javascript/utils.js, test/events/custom.test.js, test/utils.test.js
Resolves https://github.com/Financial-Times/o-tracking/issues/115
After speaking with the Data team and Tom Parker, we have come to the conclusion that circular objects are not going to be supported in Spoor and that o-tracking should throw an error if given a circular object
=> When given a circular object to send to spoor, throw a custom error message that states circular objects are not supported 

README.md, docs/event.md, package.json
I've replaced the "doesn't cut the mustard" section with a section titled "Tracking without JavaScript" as I think not everyone know what "cutting the mustard" means.
I've also added a section named "Tracking with JavaScript", which is where we can document all the o-tracking methods.
I also replaced the embedded full HTML example with a link to the example as a separate file to cut down on the readme size.
=> Restructure the readme to make it easier to find out how to track different items

docs/enrichment.md, docs/event.md
erights_id is not generated internally by o-tracking and is not used in Spoor at all. The only reference left in o-tracking is these two documentation files
=> Remove documentation about deprecated user.erights_id tracking data

MIGRATION.md, docs/membership_example.md, src/javascript/tracking.js
These utils are not required for use outside of o-tracking's codebase
=> Remove tracking.prototype.utils from the public API

src/javascript/core.js, src/javascript/core/send.js, src/javascript/core/session.js, src/javascript/core/settings.js, src/javascript/core/store.js, src/javascript/events/click.js, src/javascript/events/custom.js, src/javascript/events/page-view.js, src/javascript/tracking.js, src/javascript/utils.js, test/utils.test.js
I turned on JSDoc type-checking in my editor and came across lots of errors which stemmed from incorrect JSDoc comments. This pull-requests fixes the JSDoc so that o-tracking has no more incorrect errors. Some of the changes had to be done to the code for the JSDoc type-inference to kick in, such as replacing a reduce function with a for-of loop.
=> Improve/fix the JSDoc types being declared across the codebase

main.js, src/javascript/tracking.js, test/main.test.js
The Tracking class is only ever meant to be used as a singleton object, let's make the implementation enforce that it can only be used as a singleton and not have multiple tracking instances by mistake.
This should not change anything for users of o-tracking as the exported interface is the same.
=> Turn the tracking class into a singleton object as tracking is only meant to be used as a singleton

MIGRATION.md, src/javascript/core/send.js, test/core/send.test.js, test/events/click.test.js, test/events/custom.test.js
Previously we had the Beacon API be an opt-in system.
Every browser except for Internet Explorer now supports Beacon API (https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon#Browser_compatibility) so we should use it by default and fallback to XHR for Internet Explorer.
Beacon API was purpose built for tracking/analytics requests.
With the Beacon API, data is transmitted asynchronously when the User Agent has an opportunity to do so, without delaying the next navigation (If the browser was navigating to a new page).
=> Breaking: Always use the Beacon API if it exists.

src/javascript/tracking.js
Hopefully this is easier to understand than the for-in loop
=> Refactor: Use Object.assign instead of a for-in loop inside getDeclarativeConfig function

README.md
Fixes https://github.com/Financial-Times/o-tracking/issues/114
=> Add recommendation to use different source value for non-js tracking mode

MIGRATION.md, README.md, docs/event-parameters/page-view.md, docs/event-parameters/text-copy.md, src/javascript/core/send.js, src/javascript/core/settings.js, src/javascript/tracking.js, src/javascript/utils.js, test/core.test.js, test/core/send.test.js, test/main.test.js
Chris Brown pointed out that `is_live` currently is not used to filter out test data but that it could be if o-tracking enforced a consistent setting, which is what o-tracking will now do.
=>  Replace developer mode with test mode and send the event to Spoor with `is_live` set to false.

MIGRATION.md, src/javascript/core/store.js, test/core/store.test.js
All browsers o-tracking supports have localStorage, it does not require the cookie based fallback.
Even in incognito sessions localStorage works.
[<img width="1280" alt="browser support for localStorage" src="https://user-images.githubusercontent.com/1569131/89523263-7d1b3980-d7da-11ea-89f1-89408dd5f8e1.png">](https://caniuse.com/#feat=mdn-api_window_localstorage)
=> Remove the cookie based storage fallback

src/javascript/events/page-view.js, test/events/page.test.js
I found the original comment hard to understand so I decided to have an attempt at rewriting it.
=> update the comment about why the first call to `page` does not set a new root_id

src/javascript/events/page-view.js, src/javascript/utils.js, test/events/page.test.js, test/main.test.js
Fixes https://github.com/Financial-Times/o-tracking/issues/296
=>  Do not send multiple page-view events if the new event is the exact same as the previously sent event

src/javascript/events/click.js, src/javascript/utils.js
- Reused any existing `clicks` queue.
- Reuse any existing event delegate.
- Do not run the same callback on page view multiple times.
This will allow projects to track clicks on elements which are
not tracked with the default `oTracking.click.init` call, and
allow projects to track clicks with different event categories.
For example to track non-interactive elements with the custom
data attribute `data-my-element-to-track-clicks-on`.
```
oTracking.click.init(
'my-custom-category',
'[data-my-element-to-track-clicks-on]'
);
```
=> Improve support for multiple calls to `oTracking.click.init`.

src/javascript/events/click.js, src/javascript/events/component-view.js, src/javascript/tracking.js, test/events/click.test.js, test/events/component-view.test.js
So `oTracking.click` becomes `oTracking.click.init` and
`oTracking.view` becomes `oTracking.view.init`.
- The documentation refers to `oTracking.click.init` and
`oTracking.view.init`. `oTracking.click` and `oTracking.view` are
undocumented.
- `oTracking.page.init` already exists, each event type will align.
`oTracking.page` is a function for sending a page event where
`oTracking.page.init` is a method for firing page events 
automatically. In the future view/click could follow the same pattern
-- e.g. to track clicks on non-interactive elements
This could be considered a breaking change but I think we should
treat this as a bugfix since there are few users of v3 and the
methods being changed are not documented.
Thanks for your help, @taraojo!
=> Export an object with `init` method for `click` and `view`.

src/javascript/tracking.js
This was being set to the old major version, which could cause confusion when debugging o-tracking.
We should look at some automation to ensure this value stays in sync with the version of the component
=> Make the version property be the correct value

src/javascript/core/store.js, src/javascript/tracking.js, test/core/store.test.js
spoor-id is stored directly as a string and not an json object, which meant json.parse would throw an error and we would not be migrating the old spoor-id value to localstorage and instead would mint a new spoor-id, which is not what we want to do.
=> Fix bug where loading spoor-id from the cookie would silently fail

test/events/page.test.js
This is a bug that doesn't currently get triggered by the test runner, likely because it is the last test file to be executed, but that could change whenever karma and/or mocha is updated.
The bug is that destroy will delete the config property when what we want to do is reset the config property to it's default value, which is an empty object.
Our new test runner in obt v11 hit this bug, which is why it was spotted now
=> Bug: reset the config to it's default value instead of deleting it

src/javascript/events/click.js, src/javascript/tracking.js, test/events/click.test.js
This property is being used in some data analytics and we have been asked to add it back
I will also backport this to v3 as we need to get this out to some products straight away
=> Add back the source_id property

src/javascript/core/send.js, test/core/send.test.js
Chris Brown (Analytics team) recommends using the /ingest endpoint for the xhr and beacon requests and only using the px.gif endpoint for the fallback image transport mechanism
=> use the ingest endpoint by default and only fallback to px.gif when using the image transport mechanism

src/javascript/events/click.js, test/events/click.test.js
There's currently a bug within o-tracking v3 and v4 where it does not ensure the events in the 'clicks' queue used in o-tracking v2 are sent to spoor-api.
This is an issue because it means some events can end up never being sent. The scenario that occurs in is when a product (such as front-page) uses o-tracking v2 and a user of the product clicks a link which takes them to a different product (such as article) which uses o-tracking v3 and then the user never goes back to any products which use o-tracking v2.
The fix for this is to have o-tracking read from the 'clicks' queue which v2 uses and send all the events stored in that queue off to spoor and remove them from the queue.
Note: We should backport this to v3 as well because otherwise users on v3 could end up losing this data as well
=> Read the old clicks queue used in v2 of o-tracking and make sure all within the queue are sent to spoor

origami.json
This matches the name of the feature within polyfill.io, we have the name match polyfill.io so that the origami-build-tools can include a call to polyfill.io when running the tests on our browser support matrix
=> fix the name of the optional feature navigator.sendBeacon
